# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Matt's Bazaar
paginate:       5
baseurl:        "https://thisismattmiller.github.io/matts-bazaar/"
url:            "https://thisismattmiller.github.io/matts-bazaar/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Matt Miller
  url:          http://thisismattmiller.com
  email:        

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
